schema_version: "1.0"
id: TASK-0810
title: "Align SST stacks with backend service container"
status: blocked
blocked_reason: "Pre-commit qa:static fails: mobile typecheck errors (TS4114/TS2375 etc.) uncovered on 2025-10-23"
priority: P1
area: infra

description: >-
  Update the SST live-dev stacks so Lambda environment variables and DynamoDB resources match the refactored backend services.
  The current stack omits PROJECT_NAME/SNS_TOPIC_ARN vars and the batch-jobs table + BatchJobIdIndex required by JobRepository,
  causing runtime failures in SST deployments.

outcome: >-
  SST deployments provide the env vars and DynamoDB tables/indexes expected by createServiceContainer and JobRepository;
  presign/status/download/worker/deviceToken Lambdas boot successfully in live-dev with batch workflows intact.

scope:
  in:
    - infra/sst/stacks/api.ts
    - infra/sst/stacks/storage.ts
    - Related SST config or helper files if needed
  out:
    - Backend runtime code (no service changes in this task)
    - Terraform modules (separate infrastructure definition)

context:
  standards_tier: infra
  issues: []
  related_docs:
    - standards/infrastructure-tier.md
    - standards/cross-cutting.md
    - standards/testing-standards.md
    - ARCHITECTURE.md
  repo_paths:
    - infra/sst/stacks/api.ts
    - infra/sst/stacks/storage.ts
dependencies: []
blocked_by:
  - TASK-0816

environment:
  os: ubuntu-22.04
  runtimes:
    node: "20.x"
  tools:
    - name: pnpm
      version: "8.x"

constraints:
  approvals_required: false
  sandbox:
    filesystem: workspace-write
    network: enabled
  coding_guidelines:
    - Keep diffs minimal and focused
    - Preserve SST tagging and standards comments
  prohibited:
    - No changes to Terraform modules unless explicitly needed
    - Do not edit backend runtime code in this task

plan:
  - id: 1
    title: Confirm backend expectations
    details: Trace createServiceContainer and JobRepository env/table usage;
      list required env vars and DynamoDB resources.
    actor: agent
    inputs:
      - backend/libs/core/container/service-container.ts
      - backend/libs/core/repositories/JobRepository.ts
    outputs: []
    definition_of_done:
      - List of required env vars and tables captured in task notes
    estimate: S
    expected_files_touched: []
  - id: 2
    title: Patch SST API stack
    details: Add PROJECT_NAME/SNS_TOPIC_ARN env vars (or adjust consumers) for each Lambda;
      ensure naming matches backend expectations.
    actor: agent
    inputs: []
    outputs:
      - infra/sst/stacks/api.ts
    definition_of_done:
      - All functions receive required env vars
    estimate: M
    expected_files_touched:
      - infra/sst/stacks/api.ts
  - id: 3
    title: Extend storage stack
    details: Provision jobs batch table and BatchJobIdIndex matching backend expectations;
      update outputs as needed.
    actor: agent
    inputs: []
    outputs:
      - infra/sst/stacks/storage.ts
    definition_of_done:
      - Table and GSI names match backend configuration
    estimate: M
    expected_files_touched:
      - infra/sst/stacks/storage.ts
  - id: 4
    title: Validate
    details: Run SST diff/build checks and backend QA subset to ensure no regressions.
    actor: agent
    inputs: []
    outputs: []
    definition_of_done:
      - SST diff/build clean; backend static QA green
    estimate: S
    expected_files_touched: []

acceptance_criteria:
  - All live-dev Lambdas receive PROJECT_NAME and SNS_TOPIC_ARN (or equivalent variable consumed by NotificationService).
  - Storage stack provisions the jobs batch table plus BatchJobIdIndex expected by JobRepository.
  - `pnpm turbo run qa:static --filter=@photoeditor/backend` passes.
  - SST diff/build succeeds for the updated stacks.
  modularity:
    - "Handler LOC/complexity within budgets per standards/cross-cutting.md; no handler imports @aws-sdk/*"
    - "SST constructs keep tagging per standards/infrastructure-tier.md"
  testability:
    - "Backend static QA pipeline remains green"

validation:
  manual_checks:
    - Review SST diff to confirm env vars and table/index names match backend expectations.
  artifacts:
    - screenshots: []

deliverables:
  - infra/sst/stacks/api.ts
  - infra/sst/stacks/storage.ts

risks:
  - description: Live-dev deploy may fail if table naming mismatches existing data.
    mitigation: Run SST diff first; if destructive, plan migration or staged rollout.
