schema_version: "1.0"
id: TASK-0824
title: "Tune DynamoDB capacity and storage lifecycle per stage"
status: todo
blocked_reason: null
priority: P1
area: infra
order: null
blocked_by: []

description: >-
  Adjust the SST storage stack so DynamoDB tables honor the standards requirement for stage-aware capacity
  (on-demand for dev/stage, provisioned for production) and enable Glacier transitions on the final asset bucket.
  The current implementation keeps all tables on on-demand and skips archival rules, violating infrastructure-tier.md 12.

outcome: >-
  Production tables run with provisioned throughput sized from documented forecasts, lower environments remain on
  on-demand, and the final bucket enforces Glacier transitions while preserving existing encryption and lifecycle settings.

scope:
  in:
    - infra/sst/stacks/storage.ts
    - Associated SST helper utilities for storage configuration
    - Documentation describing throughput calculations and lifecycle rationale
  out:
    - Non-storage stacks (messaging/api)
    - Data migration tooling (tracked separately)

context:
  affected_packages: []
  standards_tier: infra
  related_docs:
    - standards/AGENTS.md
    - standards/infrastructure-tier.md
    - standards/cross-cutting.md
    - standards/testing-standards.md
    - docs/storage/forecast.md
  repo_paths:
    - infra/sst/stacks/storage.ts
    - docs/storage
  dependencies: []

environment:
  os: ubuntu-22.04
  runtimes:
    node: "20.x"
  tools:
    - name: pnpm
      version: "8.x"
  data: []

constraints:
  approvals_required: false
  sandbox:
    filesystem: workspace-write
    network: enabled
  coding_guidelines:
    - Keep SST constructs immutable and typed.
    - Reflect throughput decisions in documentation with references to forecasts.
  prohibited:
    - Do not disable encryption or change table names.

plan:
  - id: 1
    title: Gather capacity requirements
    details: >-
      Review standards/infrastructure-tier.md#database and standards/infrastructure-tier.md#storage alongside docs/storage/forecast.md to document
      provisioned throughput targets for production and justify on-demand usage elsewhere.
    actor: agent
    inputs:
      - standards/infrastructure-tier.md
      - docs/storage/forecast.md
      - standards/cross-cutting.md
    outputs:
      - docs/storage/capacity-and-lifecycle.md
    definition_of_done:
      - docs/storage/capacity-and-lifecycle.md records read/write capacity targets with citations to standards/infrastructure-tier.md#database and standards/cross-cutting.md#reliability--cost.
    estimate: S
    expected_files_touched:
      - docs/storage/capacity-and-lifecycle.md
  - id: 2
    title: Implement stage-aware capacity configuration
    details: >-
      Update infra/sst/stacks/storage.ts so DynamoDB tables follow stage-specific billing per standards/infrastructure-tier.md#database and preserve strict typing rules in standards/typescript.md#language--api-surface-rules.
    actor: agent
    inputs:
      - infra/sst/stacks/storage.ts
      - docs/storage/capacity-and-lifecycle.md
    outputs:
      - infra/sst/stacks/storage.ts
      - docs/storage/capacity-and-lifecycle.md
    definition_of_done:
      - Provisioned throughput constants and alarms are defined for production, on-demand retained for lower stages, and docs/storage/capacity-and-lifecycle.md references standards/infrastructure-tier.md#database for each decision.
    estimate: M
    expected_files_touched:
      - infra/sst/stacks/storage.ts
      - docs/storage/capacity-and-lifecycle.md
  - id: 3
    title: Add Glacier transition lifecycle rule
    details: >-
      Extend the final asset bucket lifecycle to add Glacier transitions per standards/infrastructure-tier.md#storage while keeping encryption and cleanup rules unchanged.
    actor: agent
    inputs:
      - infra/sst/stacks/storage.ts
      - docs/storage/capacity-and-lifecycle.md
    outputs:
      - infra/sst/stacks/storage.ts
      - docs/storage/capacity-and-lifecycle.md
    definition_of_done:
      - Lifecycle block transitions objects after the 90-day window specified in standards/infrastructure-tier.md#storage, and documentation notes the schedule plus monitoring hooks.
    estimate: S
    expected_files_touched:
      - infra/sst/stacks/storage.ts
      - docs/storage/capacity-and-lifecycle.md
  - id: 4
    title: Record evidence and follow-ups
    details: >-
      Capture validation steps (alarms, SST diff evidence) and any follow-up tasks in docs/storage/capacity-and-lifecycle.md, referencing standards/testing-standards.md#evidence-expectations.
    actor: agent
    inputs:
      - infra/sst/stacks/storage.ts
      - standards/testing-standards.md
    outputs:
      - docs/storage/capacity-and-lifecycle.md
      - tasks/infra
    definition_of_done:
      - docs/storage/capacity-and-lifecycle.md outlines verification steps with citations to standards/testing-standards.md#evidence-expectations and logs required follow-up tasks/IDs if provisioning adjustments are deferred.
    estimate: S
    expected_files_touched:
      - docs/storage/capacity-and-lifecycle.md

acceptance_criteria:
  must:
    - Production DynamoDB tables use provisioned throughput with values derived from forecast documentation.
    - Non-production tables explicitly retain on-demand billing with justification.
    - Final bucket applies Glacier transitions without removing existing lifecycle rules.
    - Documentation references standards/infrastructure-tier.md 12 and explains monitoring steps.
  quality_gates:
    - Affected standards references remain satisfied; note any deviations and link the follow-up standards change request.
    - No lint/type errors in affected packages.

artifacts:
  - path: docs/storage/capacity-and-lifecycle.md
    description: Evidence of throughput decisions, lifecycle configuration, and monitoring instructions.

deliverables:
  - infra/sst/stacks/storage.ts
  - docs/storage/capacity-and-lifecycle.md

risks:
  - description: Provisioned throughput misconfiguration could cause throttling or excess cost.
    mitigation: Model throughput with CloudWatch metrics, include alarms, and adjust after validation window.
