# Lean template for LLM-executable tasks (token-optimized for solo developer)
# Copy to: tasks/<area>/TASK-<id>-<short-slug>.task.yaml
# See tasks/README.md for authoring guide
#
# Standards alignment:
# - standards/global.md (universal guardrails)
# - standards/AGENTS.md (tier taxonomy)
# - Tier-specific: backend-tier.md | frontend-tier.md | shared-contracts-tier.md | infrastructure-tier.md | cross-cutting.md
# - standards/testing-standards.md (coverage expectations)
#
# Note: Integration, E2E, and mutation tests are deferred for now in this
# repository. Keep coverage thresholds in place; do not add mutation/E2E
# requirements unless explicitly reintroduced by a future ADR/task.
# If the task is blocked by an unrelated issue, set status=blocked, fill blocked_reason,
# and author a separate unblocker task referenced via blocked_by.

schema_version: "1.0"
id: TASK-0817
title: "Close mobile frontend-tier compliance gaps"
status: blocked
blocked_reason: "Broken down into subtasks for manageable implementation per standards/task-breakdown-canon.md"
blocked_by: [TASK-0818, TASK-0819, TASK-0820, TASK-0821, TASK-0822, TASK-0823]
priority: P1
area: mobile

description: >-
  Alignment review on 2025-10-23 identified that the Expo client violates multiple
  standards/frontend-tier.md guardrails: screens own feature orchestration, reusable
  UI bypasses shared tokens, state management omits RTK Query/statecharts, and
  services skip required port/adapters plus fitness evidence. This task captures the
  remediation work so the solo-maintained frontend tier remains auditable.

outcome: >-
  Mobile code, tooling, and evidence artifacts satisfy frontend-tier fitness gates for
  layered features, UI tokens, state/statecharts, and services integration, and pass
  automated qa:static + mobile tests with Storybook/Chromatic reporting in place.

scope:
  in:
    - mobile/src/screens/**/*
    - mobile/src/features/upload/**/*
    - mobile/src/store/**/*
    - mobile/src/services/**/*
    - mobile/src/lib/ui-tokens.ts
    - mobile/storybook/**/*
    - docs/ui/**/*
    - Build/test configs needed for Storybook, Chromatic, RTK Query, XState exports, and service ports
  out:
    - Backend/shared contract schema shape changes
    - Infra automation for publishing Storybook beyond Chromatic integration
    - Non-mobile clients or web frontend

context:
  affected_packages: [mobile]
  standards_tier: mobile
  issues: []
  related_docs:
    - standards/AGENTS.md
    - standards/frontend-tier.md
    - standards/typescript.md
    - standards/testing-standards.md
    - ARCHITECTURE.md
  repo_paths:
    - mobile/src
    - mobile/package.json
    - mobile/storybook
    - docs/ui
  dependencies: []

environment:
  os: ubuntu-22.04
  runtimes:
    node: "18.x"
  tools:
    - name: npm
      version: "9.x"

constraints:
  approvals_required: false
  sandbox:
    filesystem: workspace-write
    network: enabled
  coding_guidelines:
    - Keep diffs minimal and focused
    - Respect repository conventions
  prohibited:
    - No secrets or tokens in code
    - No unrelated file changes

plan:
  - id: 1
    title: Finalize remediation design
    details: >-
      Map required structural, state, and evidence changes against standards/frontend-tier.md#feature-guardrails,
      standards/frontend-tier.md#ui-components-layer, standards/frontend-tier.md#state--logic-layer, and
      standards/frontend-tier.md#services--integration-layer; document gaps and remediation notes in docs/ui/2025-frontend-tier-gap-analysis.md.
    actor: agent
    inputs:
      - standards/frontend-tier.md
      - standards/testing-standards.md
      - mobile/src
    outputs:
      - docs/ui/2025-frontend-tier-gap-analysis.md
    definition_of_done:
      - docs/ui/2025-frontend-tier-gap-analysis.md lists each gap with direct citations to standards/frontend-tier.md#feature-guardrails, #ui-components-layer, #state--logic-layer, #services--integration-layer, and links to standards/testing-standards.md#required-commands-before-pr where evidence is required.
    estimate: M
    expected_files_touched:
      - docs/ui/2025-frontend-tier-gap-analysis.md
  - id: 2
    title: Implement feature/UI layering updates
    details: >-
      Refactor screens to depend on feature `/public` exports and shared tokens per standards/frontend-tier.md#feature-guardrails
      and standards/frontend-tier.md#ui-components-layer, capturing decisions in docs/ui/2025-frontend-tier-gap-analysis.md.
    actor: agent
    inputs:
      - mobile/src/screens/HomeScreen.tsx
      - mobile/src/features/upload
      - standards/frontend-tier.md
    outputs:
      - mobile/src/screens/HomeScreen.tsx
      - mobile/src/features/upload/**/*
      - mobile/src/components/**/*
    definition_of_done:
      - Dependency-cruiser report (attached to docs/ui/2025-frontend-tier-gap-analysis.md) shows screens only import feature `/public` APIs, and shared token usage replaces ad-hoc styles in updated files with citations to standards/frontend-tier.md#feature-guardrails and #ui-components-layer.
    estimate: L
    expected_files_touched:
      - mobile/src/screens/HomeScreen.tsx
      - mobile/src/features/upload/**/*
      - mobile/src/components/**/*
  - id: 3
    title: Reinforce state/services architecture
    details: >-
      Add RTK Query slices, XState charts, and service ports/adapters aligning with standards/frontend-tier.md#state--logic-layer and
      standards/frontend-tier.md#services--integration-layer; ensure retry policies reflect cockatiel guidance and ports track evidence paths.
    actor: agent
    inputs:
      - mobile/src/store
      - mobile/src/services
      - standards/frontend-tier.md
      - standards/typescript.md
    outputs:
      - mobile/src/store/**/*
      - mobile/src/services/**/*
      - mobile/storybook/**/*
      - docs/ui/contracts/**/*
    definition_of_done:
      - Updated slices export `.scxml` or Mermaid artefacts stored under docs/ui/state-metrics with references to standards/frontend-tier.md#state--logic-layer, and service ports + adapters satisfy the 100% port fitness gate documented in docs/ui/contracts with citations to standards/frontend-tier.md#services--integration-layer and standards/typescript.md#3-analyzability.
    estimate: L
    expected_files_touched:
      - mobile/src/store/**/*
      - mobile/src/services/**/*
      - mobile/storybook/**/*
      - docs/ui/contracts/**/*
  - id: 4
    title: Backfill tests and evidence
    details: >-
      Expand component/hook tests and capture Storybook coverage plus Chromatic snapshots per standards/frontend-tier.md#ui-components-layer
      and standards/testing-standards.md#evidence-expectations; update docs/ui/storybook with links to reports.
    actor: agent
    inputs:
      - mobile/src/__tests__
      - mobile/storybook
      - standards/testing-standards.md
    outputs:
      - mobile/src/__tests__/**/*
      - docs/ui/storybook/**/*
    definition_of_done:
      - Coverage summary and Chromatic status appended to docs/ui/storybook/readme (or equivalent) citing standards/frontend-tier.md#ui-components-layer and standards/testing-standards.md#evidence-expectations, and unit tests reference stub ports with evidence noted in docs/ui/2025-frontend-tier-gap-analysis.md.
    estimate: M
    expected_files_touched:
      - mobile/src/__tests__/**/*
      - docs/ui/storybook/**/*

acceptance_criteria:
  - Screens delegate upload/edit orchestration to feature modules via `/public` exports; no cross-feature imports exist.
  - All React Native StyleSheet color/spacing tokens come from shared `ui-tokens` or lucide/react-native-svg primitives per standards/frontend-tier.md.
  - RTK Query slices + XState charts back job/upload state; `.scxml` or Mermaid exports stored under `docs/ui/state-metrics` with checksums.
  - Services expose ports under `mobile/src/services/*/port.ts` with adapters using `cockatiel` (or approved equivalent) for retry/circuit breaker.
  - Story coverage meets frontend-tier expectations; Chromatic + axe CI gates run and evidence is archived in `docs/ui/storybook`.
  - No lint/type/test regressions; `pnpm turbo run qa:static --parallel` and mobile unit suites pass.
  modularity:
    - "Feature entry points export named APIs only; layers follow screens → feature → shared UI → hooks"
    - "Adapters encapsulate platform APIs; no direct Expo/Fetch usage in feature or component layers"
    - "No cross-layer imports (dependency-cruiser enforced)"
  testability:
    - "Coverage thresholds per standards/testing-standards.md"
    - "Storybook Chromatic run reports no unresolved diffs"

validation:
  # Grouped by test agent type for orchestration

  static_checks:
    - pnpm turbo run qa:static --parallel
    - pnpm turbo run lint --filter=photoeditor-mobile
    - pnpm turbo run typecheck --filter=photoeditor-mobile

  unit_tests:
    mobile:
      - pnpm turbo run test --filter=photoeditor-mobile -- --coverage

  contract_tests: []

  manual_checks:
    - Run Chromatic UI review and confirm a11y gate passes
    - Verify mobile Test Harness screen exercises Upload flow offline/online transitions

  artifacts:
    - screenshots: [docs/ui/storybook/chromatic-summary.png]

deliverables:
  - mobile/src/features/upload/public/index.ts
  - mobile/src/services/upload/port.ts
  - mobile/src/store/uploadApi.ts
  - mobile/storybook/**
  - docs/ui/storybook/**
  - docs/ui/state-metrics/upload-statechart.scxml

risks:
  - description: RTK Query/statechart adoption may introduce regressions in existing upload flow UX.
    mitigation: Maintain parity tests via mobile Test Harness, add regression unit tests, and verify with manual harness walkthrough.
  - description: Storybook/Chromatic integration could slow CI if misconfigured.
    mitigation: Use Chromatic async workflow with `--exit-zero-on-changes` locally; document caching strategy in task notes.

# Agent output artifacts:
# - task-picker writes: .agent-output/task-picker-summary-{TASK-ID}.md (work summary)
# - test agents write: docs/tests/reports/YYYY-MM-DD-{agent-type}.md (validation results)
# - task-runner creates: changelog/YYYY-MM-DD-{topic}.md (final changelog aggregating all above)
#
# Note: Only task-runner creates the changelog; task-picker focuses on implementation.
