# Unblocker task for TASK-0820 adapter test failures
# Focus: Fix test mock infrastructure for adapter tests

schema_version: "1.0"
id: TASK-0823
title: "Fix mobile service adapter test mocks and achieve coverage thresholds"
status: obsolete
blocked_reason: "Task premise was invalid - tried to fix tests that didn't actually exist. Agent hallucinated test existence in TASK-0820. Tests were created from scratch by this task's implementer, accumulated bugs from multiple agent edits. Nuclear reset executed - test files deleted. Replaced by TASK-0826 for incremental test development."
blocked_by: []
priority: P0
area: mobile
unblocker: true
order: null


description: >-
  TASK-0820 implementation is architecturally sound but blocked by test failures caused by
  incomplete mock Response objects. Tests mock fetch but return partial objects missing required
  methods (blob(), ok, status, statusText), causing "Cannot read properties of undefined" errors.
  This task fixes test mock infrastructure and achieves coverage thresholds (80% lines, 70% branches)
  per standards/testing-standards.md.

outcome: >-
  All adapter tests pass with proper mock Response factories. Upload and notification adapters
  meet coverage thresholds (≥80% lines, ≥70% branches). Tests validate resilience policies,
  contract validation, and error handling without actual network calls.

scope:
  in:
    - mobile/src/services/upload/__tests__/adapter.test.ts (fix mocks)
    - mobile/src/services/notification/__tests__/adapter.test.ts (fix mocks)
    - mobile/src/services/__tests__/stubs.ts (create mock Response factory)
    - Test coverage improvements for both adapters
  out:
    - Adapter implementation code (no changes to mobile/src/services/*/adapter.ts)
    - Port interfaces (no changes to mobile/src/services/*/port.ts)
    - Feature layer code (no changes to screens or hooks)

context:
  affected_packages: [mobile]
  standards_tier: mobile
  issues: []
  related_docs:
    - standards/AGENTS.md
    - standards/frontend-tier.md
    - standards/testing-standards.md
    - standards/typescript.md
    - changelog/2025-10-25-TASK-0820-services-ports-adapters-blocked.md
  repo_paths:
    - mobile/src/services/upload/__tests__
    - mobile/src/services/notification/__tests__
    - mobile/src/services/__tests__
  dependencies:
    - type: task
      name: TASK-0820
      reason: This task unblocks TASK-0820 by fixing test infrastructure

environment:
  os: ubuntu-22.04
  runtimes:
    node: "18.x"
  tools:
    - name: npm
      version: "9.x"

constraints:
  approvals_required: false
  sandbox:
    filesystem: workspace-write
    network: enabled
  coding_guidelines:
    - Keep diffs minimal - only fix test mocks, do not change adapter implementations
    - Follow repository testing conventions
  prohibited:
    - No changes to adapter implementation files
    - No changes to port interface files
    - No secrets or tokens in code
  architecture:
    - "Mock Response objects must implement full Response interface (standards/testing-standards.md)"
    - "Tests validate adapter behavior without network calls (standards/frontend-tier.md)"

plan:
  - id: 1
    title: Create mock Response factory
    details: >-
      Create a factory function in mobile/src/services/__tests__/stubs.ts that generates
      full mock Response objects with all required methods (ok, status, statusText, json,
      blob, text, arrayBuffer, clone, headers, etc.).
    actor: agent
    inputs:
      - mobile/src/services/__tests__/stubs.ts (existing)
    outputs:
      - mobile/src/services/__tests__/stubs.ts (updated with createMockResponse factory)
    definition_of_done:
      - createMockResponse function returns objects matching Response interface
      - Factory supports success and error responses
      - Factory supports custom status codes, status text, and response bodies
    estimate: S
    expected_files_touched:
      - mobile/src/services/__tests__/stubs.ts

  - id: 2
    title: Fix upload adapter test mocks
    details: >-
      Update mobile/src/services/upload/__tests__/adapter.test.ts to use createMockResponse
      factory for all fetch mocks. Replace partial objects like { ok: true, json: async () => data }
      with full Response objects. Fix all 15 failing tests.
    actor: agent
    inputs:
      - mobile/src/services/upload/__tests__/adapter.test.ts
      - mobile/src/services/__tests__/stubs.ts (with createMockResponse)
    outputs:
      - mobile/src/services/upload/__tests__/adapter.test.ts (updated with proper mocks)
    definition_of_done:
      - All upload adapter tests pass
      - No "Cannot read properties of undefined" errors
      - Tests properly validate resilience policies and error handling
    estimate: M
    expected_files_touched:
      - mobile/src/services/upload/__tests__/adapter.test.ts

  - id: 3
    title: Fix notification adapter test mocks
    details: >-
      Update mobile/src/services/notification/__tests__/adapter.test.ts to use createMockResponse
      factory for all fetch mocks. Fix all 11 failing tests.
    actor: agent
    inputs:
      - mobile/src/services/notification/__tests__/adapter.test.ts
      - mobile/src/services/__tests__/stubs.ts (with createMockResponse)
    outputs:
      - mobile/src/services/notification/__tests__/adapter.test.ts (updated with proper mocks)
    definition_of_done:
      - All notification adapter tests pass
      - No "Cannot read properties of undefined" errors
      - Tests properly validate device token registration and deactivation
    estimate: M
    expected_files_touched:
      - mobile/src/services/notification/__tests__/adapter.test.ts

  - id: 4
    title: Achieve coverage thresholds
    details: >-
      Add test cases to increase coverage to meet standards (80% lines, 70% branches).
      Focus on uncovered branches (error paths, edge cases, resilience policy behavior).
    actor: agent
    inputs:
      - mobile/src/services/upload/__tests__/adapter.test.ts
      - mobile/src/services/notification/__tests__/adapter.test.ts
    outputs:
      - Updated test files with additional test cases
    definition_of_done:
      - Upload adapter: ≥80% line coverage, ≥70% branch coverage
      - Notification adapter: ≥80% line coverage, ≥70% branch coverage
      - Coverage report shows thresholds met
    estimate: M
    expected_files_touched:
      - mobile/src/services/upload/__tests__/adapter.test.ts
      - mobile/src/services/notification/__tests__/adapter.test.ts

  - id: 5
    title: Validate and document
    details: >-
      Run full test suite with coverage. Verify all adapter tests pass and coverage thresholds
      are met. Document fixes in changelog.
    actor: agent
    inputs:
      - All updated test files
    outputs:
      - changelog/2025-10-25-TASK-0823-adapter-tests-fixed.md
    definition_of_done:
      - All adapter tests pass (0 failures)
      - Coverage thresholds met for both adapters
      - Changelog documents fixes and final coverage numbers
    estimate: S
    expected_files_touched:
      - changelog/2025-10-25-TASK-0823-adapter-tests-fixed.md

acceptance_criteria:
  must:
    - All upload adapter tests pass (15/15)
    - All notification adapter tests pass (11/11)
    - Upload adapter line coverage ≥80% (currently 48.76%)
    - Upload adapter branch coverage ≥70% (currently 29.72%)
    - Notification adapter line coverage ≥80% (currently 60.67%)
    - Notification adapter branch coverage ≥70% (currently 50%)
    - Mock Response objects implement full Response interface
    - No changes to adapter implementation files
  quality_gates:
    - "Coverage thresholds per standards/testing-standards.md (80% lines, 70% branches)"
    - "No lint/type errors in mobile package"
    - "Tests validate resilience policies (retry, circuit breaker) behavior"

validation:
  static_checks:
    - pnpm turbo run qa:static --filter=photoeditor-mobile

  unit_tests:
    mobile:
      - pnpm turbo run test --filter=photoeditor-mobile -- --coverage --testPathPattern="adapter.test.ts"
      - pnpm turbo run test --filter=photoeditor-mobile -- --coverage

  contract_tests: []

  manual_checks:
    - Verify all 26 adapter tests pass (15 upload + 11 notification)
    - Review coverage report to confirm thresholds met

  artifacts:
    - screenshots: []

artifacts:
  - path: changelog/2025-10-25-TASK-0823-adapter-tests-fixed.md
    description: Documents test mock fixes and final coverage numbers
  - path: mobile/tmp/test-results/junit.xml
    description: Test execution results
  - path: mobile/coverage/coverage-summary.json
    description: Coverage metrics proving thresholds met

deliverables:
  - mobile/src/services/__tests__/stubs.ts (createMockResponse factory)
  - mobile/src/services/upload/__tests__/adapter.test.ts (fixed mocks + coverage)
  - mobile/src/services/notification/__tests__/adapter.test.ts (fixed mocks + coverage)
  - changelog/2025-10-25-TASK-0823-adapter-tests-fixed.md

risks:
  - description: Mock Response factory may not cover all Response interface methods
    mitigation: Start with minimal set (ok, status, statusText, json, blob) and add methods as needed based on test failures
  - description: Achieving 80% coverage may require testing private methods or refactoring
    mitigation: Focus on public interface and error paths; if coverage gaps remain, add edge case tests for public methods
  - description: Cockatiel resilience policies may be difficult to test properly
    mitigation: Use jest.useFakeTimers for retry delays; verify policy behavior via call counts and timing assertions
