# Lean template for LLM-executable tasks (token-optimized for solo developer)
# Subtask of TASK-0817: Frontend tier hardening
# Focus: Storybook and Chromatic infrastructure

schema_version: "1.0"
id: TASK-0821
title: "Setup Storybook and Chromatic for mobile component library"
status: todo
blocked_reason: null
blocked_by: [TASK-0818, TASK-0819, TASK-0820]
priority: P1
area: mobile

description: >-
  Part 4 of TASK-0817 frontend-tier hardening. Mobile lacks Storybook infrastructure for
  component documentation and visual regression testing. standards/frontend-tier.md mandates
  story coverage per the frontend tier standard with Chromatic baseline per commit and axe a11y
  CI gates. This subtask establishes Storybook for React Native, Chromatic integration,
  and generates coverage reports stored in docs/ui/storybook for evidence bundles.

outcome: >-
  Storybook configured for React Native with stories covering the required proportion of UI components per `standards/frontend-tier.md`.
  Chromatic integrated for visual regression testing with CI workflow. Axe a11y addon
  enabled. Coverage reports and Chromatic gate status archived in docs/ui/storybook.
  Component tests backfilled to meet coverage thresholds per `standards/testing-standards.md`.

scope:
  in:
    - mobile/storybook/**/* (new Storybook config)
    - mobile/.storybook/**/* (Storybook React Native config)
    - mobile/src/components/**/*.stories.tsx (new stories)
    - mobile/src/features/upload/components/**/*.stories.tsx (new stories)
    - mobile/src/components/__tests__/**/*.test.tsx (backfill tests)
    - docs/ui/storybook/**/* (coverage reports, Chromatic summaries)
    - mobile/package.json (Storybook dependencies)
    - .github/workflows/chromatic.yml (CI workflow)
  out:
    - UI tokens/icons migration - covered by TASK-0818
    - RTK Query/XState - covered by TASK-0819
    - Services ports/adapters - covered by TASK-0820
    - Storybook deployment infrastructure beyond Chromatic

context:
  affected_packages: [mobile]
  standards_tier: mobile
  issues: []
  related_docs:
    - standards/AGENTS.md
    - standards/frontend-tier.md
    - standards/typescript.md
    - standards/testing-standards.md
  repo_paths:
    - mobile/storybook
    - mobile/.storybook
    - mobile/src/components
    - mobile/src/features
    - docs/ui/storybook
    - .github/workflows
  dependencies:
    - type: package
      name: "@storybook/react-native"
      version: ">=6.5.0"
    - type: package
      name: chromatic
      version: ">=7.0.0"
    - type: package
      name: "@storybook/addon-a11y"
      version: ">=7.0.0"
    - type: package
      name: "@storybook/addon-interactions"
      version: ">=7.0.0"

environment:
  os: ubuntu-22.04
  runtimes:
    node: "18.x"
  tools:
    - name: npm
      version: "9.x"

constraints:
  approvals_required: false
  sandbox:
    filesystem: workspace-write
    network: enabled
  coding_guidelines:
    - Keep diffs minimal and focused
    - Respect repository conventions
  prohibited:
    - No secrets or tokens in code
    - No unrelated file changes
  architecture:
    - "Storybook + addon-a11y + addon-interactions with Chromatic baseline (standards/frontend-tier.md)"
    - "Story coverage per standards/frontend-tier.md with coverage report archived"
    - "Chromatic no-change gate; a11y violations = hard fail (standards/frontend-tier.md)"

plan:
  - id: 1
    title: Install Storybook for React Native
    details: >-
      Add @storybook/react-native and required addons so the UI layer complies with standards/frontend-tier.md#ui-components-layer
      expectations for Storybook + Chromatic coverage.
    actor: agent
    inputs:
      - mobile/package.json
      - standards/frontend-tier.md
    outputs:
      - mobile/package.json
      - pnpm-lock.yaml
    definition_of_done:
      - mobile/package.json and pnpm-lock.yaml list @storybook/react-native, @storybook/addon-a11y, @storybook/addon-interactions, and chromatic versions meeting standards/frontend-tier.md#ui-components-layer guidance.
    estimate: S
    expected_files_touched:
      - mobile/package.json
      - pnpm-lock.yaml
  - id: 2
    title: Configure Storybook for React Native
    details: >-
      Create Storybook config files (`mobile/.storybook` and `mobile/storybook`) aligning with addon requirements in standards/frontend-tier.md#ui-components-layer
      and document start commands in docs/ui/storybook/README.md.
    actor: agent
    inputs:
      - standards/frontend-tier.md
    outputs:
      - mobile/.storybook/main.js
      - mobile/storybook/index.js
      - mobile/storybook/storybook.requires.js
      - docs/ui/storybook/README.md
    definition_of_done:
      - Config files enable Storybook with addon-a11y and addon-interactions, and docs/ui/storybook/README.md notes configuration choices referencing standards/frontend-tier.md#ui-components-layer.
    estimate: M
    expected_files_touched:
      - mobile/.storybook/main.js
      - mobile/storybook/index.js
      - mobile/storybook/storybook.requires.js
      - docs/ui/storybook/README.md
  - id: 3
    title: Write stories for existing components
    details: >-
      Add stories for ErrorBoundary and UploadButton so coverage targets outlined in standards/frontend-tier.md#ui-components-layer are reachable.
    actor: agent
    inputs:
      - mobile/src/components
      - mobile/src/features/upload/components
      - standards/frontend-tier.md
    outputs:
      - mobile/src/components/ErrorBoundary.stories.tsx
      - mobile/src/features/upload/components/UploadButton.stories.tsx
    definition_of_done:
      - Stories render without runtime errors and include metadata tagging per standards/frontend-tier.md#ui-components-layer; story list documented in docs/ui/storybook/README.md.
    estimate: S
    expected_files_touched:
      - mobile/src/components/ErrorBoundary.stories.tsx
      - mobile/src/features/upload/components/UploadButton.stories.tsx
  - id: 4
    title: Configure Chromatic integration
    details: >-
      Add Chromatic npm script and CI workflow enforcing the no-change gate defined in standards/frontend-tier.md#ui-components-layer and evidence capture per standards/testing-standards.md#evidence-expectations.
    actor: agent
    inputs:
      - mobile/package.json
      - standards/frontend-tier.md
      - standards/testing-standards.md
    outputs:
      - mobile/package.json
      - .github/workflows/chromatic.yml
      - docs/ui/storybook/README.md
    definition_of_done:
      - Chromatic workflow references project token via secrets, includes axe checks, and docs/ui/storybook/README.md records workflow steps with citations to standards/frontend-tier.md#ui-components-layer and standards/testing-standards.md#evidence-expectations.
    estimate: S
    expected_files_touched:
      - mobile/package.json
      - .github/workflows/chromatic.yml
      - docs/ui/storybook/README.md
  - id: 5
    title: Generate story coverage report
    details: >-
      Produce Storybook coverage output and archive under docs/ui/storybook to meet the evidence requirement in standards/frontend-tier.md#ui-components-layer.
    actor: agent
    inputs:
      - mobile/storybook/index.js
      - standards/frontend-tier.md
    outputs:
      - docs/ui/storybook/coverage-report.json
      - docs/ui/storybook/README.md
    definition_of_done:
      - docs/ui/storybook/coverage-report.json captures component coverage metrics and README cites standards/frontend-tier.md#ui-components-layer with instructions for regenerating the report.
    estimate: S
    expected_files_touched:
      - docs/ui/storybook/coverage-report.json
      - docs/ui/storybook/README.md
  - id: 6
    title: Backfill component tests
    details: >-
      Write unit tests for ErrorBoundary and UploadButton to uphold coverage floors set in standards/testing-standards.md#coverage-expectations and front-end evidence in standards/frontend-tier.md#feature-guardrails.
    actor: agent
    inputs:
      - mobile/src/components/ErrorBoundary.tsx
      - mobile/src/features/upload/components/UploadButton.tsx
      - standards/testing-standards.md
    outputs:
      - mobile/src/components/__tests__/ErrorBoundary.test.tsx
      - mobile/src/features/upload/components/__tests__/UploadButton.test.tsx
      - docs/ui/storybook/README.md
    definition_of_done:
      - Tests stub external services, coverage summary appended to docs/ui/storybook/README.md with citations to standards/testing-standards.md#coverage-expectations and standards/frontend-tier.md#feature-guardrails.
    estimate: M
    expected_files_touched:
      - mobile/src/components/__tests__/ErrorBoundary.test.tsx
      - mobile/src/features/upload/components/__tests__/UploadButton.test.tsx
      - docs/ui/storybook/README.md
  - id: 7
    title: Document Storybook usage
    details: >-
      Finalize docs/ui/storybook/README.md with local + CI workflows, evidence locations, and references to standards/frontend-tier.md#ui-components-layer and standards/testing-standards.md#evidence-expectations.
    actor: agent
    inputs:
      - docs/ui/storybook/README.md
      - standards/frontend-tier.md
      - standards/testing-standards.md
    outputs:
      - docs/ui/storybook/README.md
    definition_of_done:
      - README outlines local dev steps, Chromatic workflow, evidence regeneration, and cites standards/frontend-tier.md#ui-components-layer plus standards/testing-standards.md#evidence-expectations.
    estimate: S
    expected_files_touched:
      - docs/ui/storybook/README.md

acceptance_criteria:
  - Storybook configured for React Native with addon-a11y and addon-interactions enabled
  - Stories exist to meet story coverage expectations per `standards/frontend-tier.md`
  - Chromatic integrated with CI workflow using --exit-zero-on-changes for local runs
  - Story coverage report saved to docs/ui/storybook/coverage-report.json
  - Component tests meet coverage thresholds per `standards/testing-standards.md`
  - No lint/type/test regressions
  modularity:
    - "Atomic Design with export barrels per atom/molecule/organism (standards/frontend-tier.md)"
  testability:
    - "Story coverage per standards/frontend-tier.md"
    - "Coverage thresholds per standards/testing-standards.md"

validation:
  static_checks:
    - pnpm turbo run qa:static --filter=photoeditor-mobile
    - test -f mobile/.storybook/main.js
    - test -f docs/ui/storybook/coverage-report.json

  unit_tests:
    mobile:
      - pnpm turbo run test --filter=photoeditor-mobile -- --coverage

  contract_tests: []

  manual_checks:
    - Run Storybook locally and verify stories render correctly
    - Run Chromatic and confirm no unresolved visual diffs
    - Verify a11y violations are reported in Storybook

  artifacts:
    - screenshots: [docs/ui/storybook/chromatic-summary.png]

deliverables:
  - mobile/.storybook/main.js
  - mobile/storybook/index.js
  - mobile/src/components/ErrorBoundary.stories.tsx
  - mobile/src/features/upload/components/UploadButton.stories.tsx
  - mobile/src/components/__tests__/ErrorBoundary.test.tsx
  - mobile/src/features/upload/components/__tests__/UploadButton.test.tsx
  - docs/ui/storybook/coverage-report.json
  - docs/ui/storybook/README.md
  - .github/workflows/chromatic.yml

risks:
  - description: Storybook/Chromatic integration could slow CI if misconfigured
    mitigation: Use Chromatic async workflow with --exit-zero-on-changes locally; document caching strategy
  - description: React Native Storybook may have compatibility issues with Expo
    mitigation: Use latest @storybook/react-native version; test with Expo dev client
